Update README.md to add to samples search page
Azure-Samples/function-javascript-ai-openai-chatgpt pull request #6
Opened 2024-01-03 20:49 UTC by spboyer

2024-01-03 20:50 UTC, spboyer commented
adds template to https://learn.microsoft.com/en-us/samples/browse/?expanded=azure&languages=azdeveloper

2024-04-29 15:08 UTC, paulyuk requested changes
LGTM with change

2024-04-29 15:08 UTC, paulyuk commented on README.md
> +- typescript
```suggestion
```

2024-04-29 15:08 UTC, paulyuk commented on README.md
> +- typescript
Like except it's not typescript

2024-04-29 15:10 UTC, merged